# Generated by Django 4.2.4 on 2023-08-28 22:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allcars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('abs', 'Anti-lock Braking System (ABS)'), ('airbags', 'Airbags'), ('air_conditioning', 'Air Conditioning'), ('cruise_control', 'Cruise Control'), ('power_windows', 'Power Windows'), ('power_steering', 'Power Steering'), ('keyless_entry', 'Keyless Entry'), ('navigation_system', 'Navigation System'), ('bluetooth', 'Bluetooth Connectivity'), ('backup_camera', 'Backup Camera'), ('parking_sensors', 'Parking Sensors'), ('heated_seats', 'Heated Seats'), ('sunroof', 'Sunroof'), ('leather_seats', 'Leather Seats'), ('alloy_wheels', 'Alloy Wheels'), ('fog_lights', 'Fog Lights'), ('automatic_transmission', 'Automatic Transmission'), ('all_wheel_drive', 'All-Wheel Drive (AWD)'), ('four_wheel_drive', 'Four-Wheel Drive (4WD)'), ('convertible', 'Convertible'), ('electric_windows', 'Electric Windows'), ('cd_player', 'CD Player'), ('mp3_player', 'MP3 Player')], max_length=300),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Barishal', 'Barishal'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ("Cox's Bazar", "Cox's Bazar"), ('Jessore', 'Jessore'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Comilla', 'Comilla'), ('Bogra', 'Bogra'), ('Tangail', 'Tangail'), ('Dinajpur', 'Dinajpur'), ('Kushtia', 'Kushtia'), ('Brahmanbaria', 'Brahmanbaria'), ('Feni', 'Feni'), ('Jamalpur', 'Jamalpur'), ('Noakhali', 'Noakhali'), ('Pabna', 'Pabna'), ('Naogaon', 'Naogaon'), ('Sirajganj', 'Sirajganj'), ('Moulvibazar', 'Moulvibazar'), ('Satkhira', 'Satkhira'), ('Faridpur', 'Faridpur'), ('Lalmonirhat', 'Lalmonirhat'), ('Bagerhat', 'Bagerhat'), ('Pirojpur', 'Pirojpur'), ('Bhola', 'Bhola'), ('Chandpur', 'Chandpur'), ('Chuadanga', 'Chuadanga'), ('Habiganj', 'Habiganj'), ('Jhenaidah', 'Jhenaidah'), ('Khagrachari', 'Khagrachari'), ('Meherpur', 'Meherpur'), ('Munshiganj', 'Munshiganj'), ('Narail', 'Narail'), ('Lakshmipur', 'Lakshmipur'), ('Rangamati', 'Rangamati'), ('Netrokona', 'Netrokona'), ('Sherpur', 'Sherpur'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District Of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=100),
        ),
    ]
